#! /bin/sh

echo "network up `date`" >> /home/tonis/connection.log
is_local=$(ping -c 1 kivirik.local | grep "1 received")

if [ "$is_local"  ]
then
 echo "connected to local" >> /home/tonis/connection.log
 ufw allow ssh
 sed -i -r '/kivirik\.ee$/s/^#*//g' /etc/hosts
else
 echo "connected to other network" >> /home/tonis/connection.log
 ufw deny ssh
 sed -i -r '/kivirik\.ee$/s/^#*/#/g' /etc/hosts
fi

exit 0
